stages:
    - publish
    - deploy

variables:
    TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

publish:
    image: docker:latest
    stage: publish
    services:
        - docker:dind
    script:
        - docker login -u $SSH_USER -p $PAT $CI_REGISTRY
        - docker build -t $TAG_COMMIT -t $TAG_LATEST .
        - docker push $TAG_COMMIT
        - docker push $TAG_LATEST

deploy:
    image: alpine:latest
    stage: deploy
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - apk update && apk add openssh-client
        - ssh $SSH_USER@$SSH_HOST "docker login -u $SSH_USER -p $PAT $CI_REGISTRY"
        - ssh $SSH_USER@$SSH_HOST "docker pull $TAG_COMMIT"
        - ssh $SSH_USER@$SSH_HOST "docker container rm -f portfolio || true"
        - ssh $SSH_USER@$SSH_HOST "docker run -d -p 9000:3000 --name portfolio $TAG_COMMIT"
    environment:
        name: production
        url: http://$SSH_HOST
    only:
        - main
